config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: 'can only have one list assigned' }
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

# A list must have a unique name.

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

# A movie must have a unique title.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark[:list_id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container my-4 text-white">
  <h1>New Bookmark</h1>

  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "Add movie", class: "btn btn-outline-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="/">
        <i class="fas fa-ticket-alt text-white"></i>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create new list", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!-- All Lists page -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path("https://res.cloudinary.com/dxojr5jr7/image/upload/v1621019630/Sam-Neill-in-the-Mouth-of-Madness_copy_hzwjun.jpg") %>);">
  <div class="container">
    <h1 id="header-text">Moviemarks</h1>
    <p id="header-subtext">What to watch next!</p>
  </div>
</div>

<br>

<div class="container">
  <div class="d-grid gap-2">
    <%= link_to "Add new list", new_list_path, class: "btn btn-secondary btn-lg" %>
  </div>

  <br>

  <ul class="list-inline">
    <% @lists.each do |list| %>
      <li class="my-5">
        <div class="card-category" style="max-width: 1000px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(list.photo.key) %>)">
          <%= link_to list.name, list_path(list), class: "text-white text-decoration-none" %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container my-4 text-white">
  <h1>Add new list</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name, label: "List Name" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-outline-success" %>
  <% end %>

  <br>

  <%= link_to "Cancel", root_path, class: "btn btn-outline-secondary" %>
</div>

app/views/lists/show.html.erb
<!-- movies included in @list to be displayed here -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@list.photo.key) %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<br>


<div class="container">
  <ul class="list-inline">
    <% @list.movies.each do |movie| %>
      <li>
        <div class="card mb-3" style="max-width: 600px;">
          <div class="row g-0">
            <div class="col-md-4">
              <%= image_tag movie.poster_url, alt: "Bill Murray" %>
            </div>
            <div class="col-md-8">
              <div class="card-body bg-light">
                <div class="card-header"><strong><%= movie.title %></strong></div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item"><%= movie.bookmarks.first.comment %></li>
                  <li class="list-group-item d-flex justify-content-between">
                    Rating: <%= movie.rating %>
                    <%= link_to "Remove film", bookmark_path(movie.bookmarks.ids), class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure??' } %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="container footer-nav">
    <%= link_to "Add new bookmark", new_list_bookmark_path(@list), class: "btn btn-outline-success" %>
    <%= link_to "Back to all lists", root_path, class: "btn btn-outline-secondary"  %>
  </div>
  <%#= link_to "Remove film", bookmark_path(movie.bookmark_ids), class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure??' } %>
</div>